parameters:
    products_directory: '%kernel.project_dir%/public/uploads/products'
    carousel_directory: '%kernel.project_dir%/public/uploads/carousel'
    app.secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    # Default configuration for services
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $mailer: '@Symfony\Component\Mailer\MailerInterface'

    # Makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # Explicit service configurations
    App\Service\StripePayment:
        arguments:
            $clientSecret: '%env(STRIPE_SECRET_KEY)%'
            $webhookSecret: '%env(WEBHOOK_SECRET_KEY)%'

    App\Service\Payment:
        arguments:
            $requestStack: '@request_stack'
            $stripePayment: '@App\Service\StripePayment'

    App\Security\LoginFormAuthenticator:
        arguments: [ ]


    App\EventListener\KernelListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    App\Service\NotificationService: ~